### ISSUE TITLE
暗色主题问题和加载问题

### ISSUE THREAD

**Issue by Shiharoku** [ZJU-CC98/CC98-PWA#10]
1. 暗色主题中引用内容模糊不清，亮色底白字影响阅读（可以调）

![photo_2018-11-11_16-12-35](https://user-images.githubusercontent.com/7569008/48310641-07664780-e5cd-11e8-8910-232c9a44bddd.jpg)

2. 刷新按钮导致暗色主题失效（不碍事）

3. **98deleter 导致的楼层加载失败问题，测试了好几次，应该是当一页中出现 98deleter 的时候，加载完前一页的内容后就无法继续加载。（感觉很重要）**

演示帖子地址 /topic/4803174/2#1

**Comment by AsukaSong** [comment]
@Dearkano

**Comment by Dearkano** [comment]
1.暗色主题的UBB解析还没有完成，@adddna 在做
2.本地env的储存还没有存到localstorage
3.等下去看看....

感谢反馈

**Comment by Shiharoku** [comment]
谢谢，了解了，辛苦辛苦

**Comment by Dearkano** [comment]
第三个问题的反馈：
98delete删除后导致风评属性变为null而不是[]，做了相关处理，之后在v0.10.3中推送

**Comment by Dearkano** [comment]
暗色主题UBB已完成
