### ISSUE TITLE
各页面URL保持与网页版保持一致？

### ISSUE THREAD

**Issue by zjuchenyuan** [ZJU-CC98/CC98-PWA#2]
`/newTopic` -> `/newTopics`

`/user/666` -> `/user/id/666`

**Comment by Deturium** [comment]
URL 为什么需要一致呢？

**Comment by zjuchenyuan** [comment]
在测试时经常需要比较当前特性应该具备的行为 如对不规范的ubb解析、故障影响范围排查
保持url一致便于快速跳转到官网查看对应的标准结果
只需修改域名而无需考虑手工修改url构造

进而可以做单域名自动区分手机与电脑访问
