### ISSUE TITLE
无限加载在页面高度足够当前所有内容时不会触发加载

### ISSUE THREAD

**Issue by zjuchenyuan** [ZJU-CC98/CC98-PWA#3]
在电脑上访问如图所示 由于窗口高度足够显示所有内容 没有滚动条出现

只有把页面缩小至滚动条出现 滚动到底部才会触发加载

底部的圈圈会给人误导

![image](https://user-images.githubusercontent.com/17289004/47847446-3aa71a80-de06-11e8-924b-60210e75c16d.png)

**Comment by Dearkano** [comment]
新版本暂时没有发现此问题

**Comment by Deturium** [comment]
复现方法：
    PC 端访问，调低屏幕缩放至新帖页面能一次性放下初始十条和滚动条
    访问新帖页面

考虑解法：
    loading 条转一定时间后变为重新加载按钮，允许重新触发
