### ISSUE TITLE
搜索页面显示时间的bug？

### ISSUE THREAD

**Issue by yujincheng08** [ZJU-CC98/CC98-PWA#35]
![Screenshot_2019-03-10-17-51-18-841_com android chrome](https://user-images.githubusercontent.com/5022927/54083383-724a4400-435d-11e9-9851-4a0a5e8c6eb2.png)
这里的第一个帖子说是4年前，然而实际是4个月前的？

**Comment by Dearkano** [comment]
感谢提出，搜索页面目前显示最后回复时间，下沉功能修改了最后回复时间导致显示上出现逻辑问题，下个版本会统一修正为发帖时间。

**Comment by yujincheng08** [comment]
666，修复得这么快👍
